#!/usr/bin/env python
from __future__ import print_function, division, unicode_literals

"""
Script to edit DSUP files to allow user FITS headers.

Enabling user FITS headers is a three step process.

1) Edit DSUP files.

Run this script to update the DSUP files to contain header items and default values
defined below.

2) Edit the dictionary.

The ESO dictionary (/introot/observer/config/ESO-VLT-DIC.NGCDCS) needs editing to
contain a suitable entry for every field in the header_items dictionary.

3) Recompile the IR software.

Either run the irRebuild.sh script or,

cd ~/hipircfg/src
make install
"""

import glob
import os
import shutil


header_items = dict(
    OBSERVER='None',
    FILTERS='ugriz',
    PROGRAMME='GTO',
    PI="None",
    RUNCOM='None',
    IMAGETYP="BIAS"
)


def backup_dsup_file(path):
    shutil.copy(path, path+'.bak')


def insert_header_items(path):
    hdr = """
#
# USER HEADER INFO
#
"""
    lines = open(path).readlines()
    already_done = any([line.startswith('OBSERVER') for line in lines])
    if already_done:
        return
    lines.pop()  # remove end line
    with open(path, 'w') as f:
        for line in lines:
            f.write(line)
        f.write(hdr)
        for item in header_items:
            f.write('{}\t{}\n'.format(item, header_items[item]))
        f.write('# --- oOo ---')


dsup_path = os.path.expanduser('~/hipircfg/config/NGCIRSW')
dsup_files = glob.glob(os.path.join(dsup_path, 'hipercam*.dsup'))
for path in dsup_files:
    backup_dsup_file(path)
    insert_header_items(path)
