#!/usr/bin/env python
from __future__ import print_function, division, unicode_literals

import argparse
import os
from six.moves.urllib.request import urlretrieve

URL_TEMPLATE = 'http://gtc-phase2.gtc.iac.es/science/Parser/sequences/GTC{id:03d}-{semester:s}_{obid:04d}.json'
FNAME_TEMPLATE = 'GTC{id:03d}-{semester:s}_{obid:04d}.json'


def download_json(proposal_id, semester, obid):
    pars = dict(id=proposal_id, semester=semester, obid=obid)
    dir = os.path.join(os.path.expanduser('~/.hdriver'), 'apps')
    fname = os.path.join(dir, FNAME_TEMPLATE.format(**pars))
    url = URL_TEMPLATE.format(**pars)
    urlretrieve(url, fname)


if __name__ == "__main__":

    # command-line parameters
    parser = argparse.ArgumentParser(description='Download GTC JSON files for instrument setup')
    parser.add_argument('proposal_id', type=int, help='Proposal ID number (e.g 100)')
    parser.add_argument('semester', type=str, help='Semester (e.g 17B)')
    parser.add_argument('obid', type=int, help='Observing block id number (e.g 2)')
    args = parser.parse_args()

    download_json(args.proposal_id, args.semester, args.obid)
    print('Download complete - load JSON file from hdriver')
