#!/usr/bin/env python
from __future__ import print_function, division, unicode_literals

import numpy as np
import matplotlib.pyplot as plt
import time

from hcam_drivers.globals import Container
from hcam_drivers.config import load_config
from hcam_drivers.hardware import honeywell, meerstetter, unichiller, vacuum
from astropy.time import Time
from astropy import units as u


if __name__ == "__main__":
    g = Container()
    g.cpars = dict()
    load_config(g)
    cpars = g.cpars

    gauges = [vacuum.PDR900(cpars['termserver_ip'], port) for port in cpars['vacuum_ports']]
    ms = meerstetter.MeerstetterTEC1090(cpars['meerstetter_ip'][0], 50000)

    plt.ion()


    start = Time.now()
    xp = []
    y1 = []
    y2 = []
    plt.plot(xp, y1, 'r-', label='Pressure 1')
    plt.plot(xp, y2, 'b-', label='Pressure 2')
    plt.xlabel('Time (hours)')
    plt.ylabel('Pressure (mbar)')
    plt.legend()

    with open('hw_log.txt', 'a') as log:
        while True:
            pressures = [1000*gauge.pressure.value for gauge in gauges]
            #ccd_temps = [ms.get_ccd_temps(ccd) for ccd in (1,2)]
            #hs_temps = [ms.get_heatsink_temp(ccd) for ccd in (1,2)]
            #powers = [ms.get_power(ccd) for ccd in (1,2)]
            x = Time.now()
            log.write('{} {} {}\n'.format(
                x.mjd, pressures[0], pressures[1]
            ))
            xp.append((x - start).to(u.hour).value)
            y1.append(pressures[0])
            y2.append(pressures[1])
            print(xp, pressures[0], pressures[1])

            plt.gca().lines[0].set_xdata(xp)
            plt.gca().lines[1].set_xdata(xp)
            plt.gca().lines[0].set_ydata(y1)
            plt.gca().lines[1].set_ydata(y2)

            plt.gca().relim()
            plt.gca().autoscale_view()
            plt.gca().set_ylim((1e-5, 1e-2))
            plt.pause(20)

    while True:
        plt.pause(0.05)
