#!/usr/bin/env python
from __future__ import print_function, division, unicode_literals
import tqdm

from six.moves import queue
from hcam_widgets.misc import (FifoThread, get_hardware_value,
                               set_hardware_value)
from hcam_widgets.globals import Container
from hcam_drivers.config import load_config
from hcam_drivers.hardware import slide


usage = """
'slide' controls the focal plane slide; it takes a single argument,
with the following possible forms:

    home         -- return the slide to its home position
    park         -- move the focal plane just out of the field
    position     -- return the current slide position
    reset        -- equivalent to powering off and then on
    stop         -- stop the device during a move
    enable       -- enable potentiometer on back of slide
    disable      -- disable potentiometer on back of slide
    +<off>       -- add 'off' pixels to current position
    -<off>       -- subtract 'off' pixels from current position
    pos=<pos>    -- go to absolute position of 'pos' pixels

    Hitting <Ctrl-C> will terminate a move that has already started.
"""

MIN_TIMEOUT = 2  # seconds


def action(command, estimated_time, args=()):
    """
    Run a long running slide command, stopping on <Ctrl-C>
    """
    errq = queue.Queue()
    tstep = 0.1
    pbar = tqdm.tqdm(total=int(estimated_time/tstep),
                     ncols=40, leave=False,
                     bar_format='{l_bar}{bar} | {remaining}')
    t = FifoThread('Slide', command, errq, args=args)
    t.start()
    try:
        while t.is_alive():
            pbar.update(1)
            t.join(timeout=tstep)

    except KeyboardInterrupt:
        raise  # re-raise so calling thread can stop slide

    # handle exceptions raised in thread
    try:
        exc = errq.get(block=False)
    except queue.Empty:
        pass
    else:
        name, error, tback = exc
        print('\n\nError in slide thread: {}'.format(error))
        # print(tback)


def parse_position(pos_str):
    return float(pos_str.split('=')[1].split()[0])


if __name__ == "__main__":

    # read defaults from hdriver config file
    g = Container()
    g.cpars = dict()
    load_config(g)
    cpars = g.cpars

    import sys
    try:
        comm = sys.argv[1]
    except IndexError:
        print(usage)
        sys.exit(-1)

    timeout = MIN_TIMEOUT

    if comm == 'home':
        def command():
            value, msg = set_hardware_value(cpars, 'slide', 'home')
            print('\n\n'+msg)

    elif comm == 'park':
        def command():
            value, msg = set_hardware_value(cpars, 'slide', 'position', slide.UNBLOCK_POS)
            print('\n\n'+msg)

    elif comm == 'position':
        def command():
            print('\n\n'+get_hardware_value(cpars, 'slide', 'position'))

    elif comm == 'reset':
        def command():
            msg = set_hardware_value(cpars, 'slide', 'reset')
            print('\n\n'+msg)

    elif comm == 'stop':
        def command():
            val, msg = set_hardware_value(cpars, 'slide', 'stop')
            print('\n\n'+msg)

    elif comm == 'enable':
        def command():
            msg = set_hardware_value(cpars, 'slide', 'enable')
            print('\n\n'+msg)

    elif comm == 'disable':
        def command():
            msg = set_hardware_value(cpars, 'slide', 'disable')
            print('\n\n'+msg)

    elif comm.startswith('+'):
        try:
            offset = int(comm[1:])
        except ValueError:
            raise ValueError('offset {} not understood'.format(comm))

        def command():
            current_position = parse_position(get_hardware_value(cpars, 'slide', 'position'))
            new_position = current_position + offset
            value, msg = set_hardware_value(cpars, 'slide', 'position', new_position)
            print('\n\n'+msg)

    elif comm.startswith('-'):
        try:
            offset = int(comm[1:])
        except ValueError:
            raise ValueError('offset {} not understood'.format(comm))

        def command():
            current_position = parse_position(get_hardware_value(cpars, 'slide', 'position'))
            new_position = current_position - offset
            value, msg = set_hardware_value(cpars, 'slide', 'position', new_position)
            print('\n\n'+msg)

    elif comm.startswith('pos='):
        try:
            position = int(comm.split('=')[1])
        except ValueError:
            raise ValueError('position {} not understood'.format(comm))

        def command():
            value, msg = set_hardware_value(cpars, 'slide', 'position', position)
            print('\n\n'+msg)

    else:
        print('Command not recognised!')
        print(usage)

    try:
        action(command, timeout)
    except KeyboardInterrupt:
        # handle keyboardinterrupt
        msg = set_hardware_value(cpars, 'slide', 'stop')
        print('\n\n'+msg)
